import { Link } from "react-router-dom";
import type { Suggestion } from "../lib/api";
import { parseTicker } from "../lib/tickers";
import Confidence from "./Confidence";
import DirectionBadge from "./DirectionBadge";
import HeaderTooltip from "./HeaderTooltip";

// Tooltip text per column header. Hover the column name to read it.
const TOOLTIPS: Record<string, string> = {
  Date: "Date the suggestion was generated by the daily pipeline.",
  Ticker:
    "Stock or ETF symbol. Click to open the per-ticker grid view across all timeframes and risk profiles.",
  Exchange:
    "Where this listing trades. Suffix in the data (.L, .DE, …) is what yfinance uses; we show the friendly name here.",
  Risk:
    "Risk profile this suggestion is tailored to. " +
    "Conservative = capital-preservation bias; Balanced = even mix; " +
    "Growth = momentum + fundamentals; Aggressive = high-volatility tolerant.",
  TF:
    "Time horizon — how far out this call is meant to play out. " +
    "1w / 2w / 1m / 3m / 6m / 1y / 3y. The target date is suggestion date + this window.",
  Direction:
    "BUY = bullish enough to act on. " +
    "AVOID = no clear signal — pass on this trade. " +
    "SELL-SHORT = bearish enough to short (or sell if you already hold it). " +
    "T212 Invest doesn't allow shorts, so SELL-SHORT is best read as 'don't buy / consider selling existing position'.",
  Conf:
    "Confidence in the call. Color-graded: green ≥ 70%, yellow ≥ 50%, gray below. " +
    "Tag '(raw)' means uncalibrated — the system needs ≥50 validated outcomes before " +
    "the calibration model kicks in and converts raw → realized hit rate.",
  "Entry €":
    "Suggested entry price in EUR. Native-currency price + FX conversion via FRED rates.",
  "Target €":
    "Profit target in EUR — distance from entry scales with timeframe (more for longer horizons).",
  "Stop €":
    "Stop-loss in EUR — risk control. Roughly half the target distance, giving ~2:1 reward/risk.",
  "Target date":
    "When this suggestion's window closes. The validation sweep grades it after this date.",
  Headline:
    "One-line summary of the thesis. Click to open the full structured rationale " +
    "(technical case, fundamentals, sentiment, risks, invalidation, tax angle).",
};

function HeaderCell({ name, className = "" }: { name: string; className?: string }) {
  return <HeaderTooltip name={name} tip={TOOLTIPS[name]} className={className} />;
}

export default function SuggestionTable({
  suggestions,
}: {
  suggestions: Suggestion[];
}) {
  if (suggestions.length === 0) {
    return (
      <div className="rounded border border-border bg-panel/30 p-6 text-sm text-gray-400">
        No suggestions match the current filters.
      </div>
    );
  }

  return (
    <div className="rounded border border-border overflow-hidden">
      <table className="w-full text-sm">
        <thead className="bg-panel/60 text-gray-400 text-left">
          <tr>
            <HeaderCell name="Date" />
            <HeaderCell name="Ticker" />
            <HeaderCell name="Exchange" />
            <HeaderCell name="Risk" />
            <HeaderCell name="TF" />
            <HeaderCell name="Direction" />
            <HeaderCell name="Conf" />
            <HeaderCell name="Entry €" />
            <HeaderCell name="Target €" />
            <HeaderCell name="Stop €" />
            <HeaderCell name="Target date" />
            <HeaderCell name="Headline" className="max-w-xl" />
          </tr>
        </thead>
        <tbody>
          {suggestions.map((s) => {
            const t = parseTicker(s.ticker);
            return (
              <tr
                key={s.id}
                className="border-t border-border hover:bg-panel/30 cursor-pointer"
              >
                <td className="px-3 py-2 text-gray-400">{s.suggestion_date}</td>
                <td className="px-3 py-2">
                  <Link
                    to={`/ticker/${encodeURIComponent(s.ticker)}`}
                    className="font-mono hover:text-accent"
                    title={`${t.full} — click for the per-ticker grid`}
                  >
                    {t.display}
                  </Link>
                </td>
                <td
                  className="px-3 py-2 text-xs text-gray-400"
                  title={t.exchangeFull}
                >
                  {t.exchange}
                </td>
                <td className="px-3 py-2 capitalize">{s.risk_profile}</td>
                <td className="px-3 py-2 font-mono">{s.timeframe}</td>
                <td className="px-3 py-2">
                  <DirectionBadge direction={s.direction} />
                </td>
                <td className="px-3 py-2">
                  <Confidence raw={s.confidence} calibrated={s.confidence_calibrated} />
                </td>
                <td className="px-3 py-2 font-mono text-gray-300">
                  {fmt(s.entry_price_eur)}
                </td>
                <td className="px-3 py-2 font-mono text-gray-300">
                  {fmt(s.target_price_eur)}
                </td>
                <td className="px-3 py-2 font-mono text-gray-300">
                  {fmt(s.stop_loss_eur)}
                </td>
                <td className="px-3 py-2 text-gray-400">{s.target_date}</td>
                <td className="px-3 py-2 text-gray-300">
                  <Link to={`/suggestion/${s.id}`} className="hover:text-accent">
                    {s.headline ?? "—"}
                  </Link>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function fmt(n: number | null): string {
  if (n == null) return "—";
  return n.toLocaleString(undefined, { maximumFractionDigits: 2 });
}
